name = "sooriya-analytics"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "sooriya-analytics"
# database_id = "local"
database_id = "25bff25f-8447-452c-ab3c-322c71be18a3"

[dev]
port = 8787
local_protocol = "http"
